<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Bicep.Local.Extension" Version="0.38.33" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference
          Include="..\BicepLocalExtension.SourceGenerator\BicepLocalExtension.SourceGenerator.csproj"
          OutputItemType="Analyzer"
          ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
