using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace BicepLocalExtension.SourceGenerator;

/// <summary>
/// Incremental source generator that scans the compilation for every class that
/// directly or indirectly derives from
/// <c>Bicep.Local.Extension.Host.Handlers.TypedResourceHandler&lt;,&gt;</c> or
/// <c>TypedResourceHandler&lt;,,&gt;</c> and emits a single extension method
/// <c>WithAllResourceHandlers(this IBicepExtensionBuilder)</c> that registers
/// them all, removing the need to list each handler manually in Program.cs.
/// </summary>
[Generator]
public sealed class ResourceHandlerRegistrationGenerator : IIncrementalGenerator
{
    private const string TypedResourceHandlerFullName =
        "Bicep.Local.Extension.Host.Handlers.TypedResourceHandler";

    private const string BicepExtensionBuilderFullName =
        "Microsoft.Extensions.DependencyInjection.IBicepExtensionBuilder";

    private const string GeneratedNamespace =
        "BicepLocalExtension";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all class declarations that are candidates (partial classes
        // or concrete classes — we filter properly in the semantic step).
        IncrementalValuesProvider<INamedTypeSymbol> handlerSymbols = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHandlerSymbol(ctx))
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);

        // Collect all discovered handlers into a single list for the final emit.
        IncrementalValueProvider<IReadOnlyList<INamedTypeSymbol>> allHandlers =
            handlerSymbols.Collect()
                          .Select(static (arr, _) => (IReadOnlyList<INamedTypeSymbol>)arr);

        context.RegisterSourceOutput(allHandlers, static (spc, handlers) =>
        {
            if (handlers.Count == 0)
                return;

            var source = BuildSource(handlers);
            spc.AddSource("ResourceHandlerRegistrations.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    // ── Semantic filter ───────────────────────────────────────────────────────

    private static INamedTypeSymbol? GetHandlerSymbol(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
            return null;

        // Skip abstract classes — we only want concrete handlers.
        if (symbol.IsAbstract)
            return null;

        return DerivesFromTypedResourceHandler(symbol) ? symbol : null;
    }

    private static bool DerivesFromTypedResourceHandler(INamedTypeSymbol? symbol)
    {
        var current = symbol?.BaseType;
        while (current is not null)
        {
            // Match both TypedResourceHandler<,> and TypedResourceHandler<,,>
            if (current.IsGenericType &&
                current.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .StartsWith($"global::{TypedResourceHandlerFullName}"))
            {
                return true;
            }
            current = current.BaseType;
        }
        return false;
    }

    // ── Code emission ─────────────────────────────────────────────────────────

    private static string BuildSource(IReadOnlyList<INamedTypeSymbol> handlers)
    {
        // Deduplicate (incremental pipeline may surface duplicates in edge cases).
        var distinct = handlers
            .GroupBy(h => h.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Select(g => g.First())
            .OrderBy(h => h.Name)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {GeneratedNamespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated extension method that registers all resource handlers.");
        sb.AppendLine("/// Re-generated whenever a class deriving from TypedResourceHandler is added or removed.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ResourceHandlerRegistrationExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers all {distinct.Count} resource handler(s) discovered in this assembly.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static {BicepExtensionBuilderFullName} WithAllResourceHandlers(");
        sb.AppendLine($"        this {BicepExtensionBuilderFullName} builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        return builder");

        for (var i = 0; i < distinct.Count; i++)
        {
            var fqn = distinct[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var isLast = i == distinct.Count - 1;
            sb.AppendLine($"            .WithResourceHandler<{fqn}>(){(isLast ? ";" : string.Empty)}");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

